[app]
13.60.251.87 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/shelfsense-key.pem

[db]
13.62.51.191 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/shelfsense-key.pem

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
